### ISSUE TITLE
Error message with nodejs 8.9

### ISSUE THREAD

**Issue by rijotech** [johnpolacek/controldeck.js#11]
/home/rijotech/controldeck.js/node_modules/node-static/lib/node-static.js:220
        headers['content-type']   = mime.lookup(files[0]);

TypeError: mime.lookup is not a function
    at Server.respond (/home/rijotech/controldeck/node_modules/node-static/lib/node-static.js:220:42)
    at /home/rijotech/controldeck/node_modules/node-static/lib/node-static.js:59:18
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by Ibanezmtm1** [comment]
go to \node_modules\node-static\lib\node-static.js
on line 7 
, mime = require('mime');
=>
, mime = require('mime-types');
