### ISSUE TITLE
Install in ubuntu 13.10 (node v0.6.19, npm 1.1.4)

### ISSUE THREAD

**Issue by macsteu** [johnpolacek/controldeck.js#9]
Hi, I am trying to install through the npm command on ubuntu 13.10, but I receive the following error, I'm wondering what I am doing wrong..

verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
info using npm@1.1.4
info using node@v0.6.19
verbose config file /home/stefano/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
verbose caching /home/stefano/controldeck.js-master/package.json
verbose loadDefaults controldeck@0.0.0
verbose readDependencies: using package.json deps
verbose where, deps [ '/home/stefano/controldeck.js-master',
verbose where, deps   [ 'node-static', 'socket.io' ] ]
verbose from cache /home/stefano/controldeck.js-master/package.json
info preinstall controldeck@0.0.0
verbose from cache /home/stefano/controldeck.js-master/package.json
verbose readDependencies: using package.json deps
verbose cache add [ 'node-static@~0.6.6', null ]
silly cache add: name, spec, args [ undefined,
silly cache add: name, spec, args   'node-static@~0.6.6',
silly cache add: name, spec, args   [ 'node-static@~0.6.6', null ] ]
verbose parsed url { pathname: 'node-static@~0.6.6',
verbose parsed url   path: 'node-static@~0.6.6',
verbose parsed url   href: 'node-static@~0.6.6' }
silly cache add: name, spec, args [ 'node-static', '~0.6.6', [ 'node-static', '~0.6.6' ] ]
verbose parsed url { pathname: '~0.6.6', path: '~0.6.6', href: '~0.6.6' }
verbose addNamed [ 'node-static', '~0.6.6' ]
verbose addNamed [ null, '>=0.6.6- <0.7.0-' ]
silly name, range, hasData [ 'node-static', '>=0.6.6- <0.7.0-', false ]
verbose cache add [ 'socket.io@~0.9.13', null ]
silly cache add: name, spec, args [ undefined, 'socket.io@~0.9.13', [ 'socket.io@~0.9.13', null ] ]
verbose parsed url { pathname: 'socket.io@~0.9.13',
verbose parsed url   path: 'socket.io@~0.9.13',
verbose parsed url   href: 'socket.io@~0.9.13' }
silly cache add: name, spec, args [ 'socket.io', '~0.9.13', [ 'socket.io', '~0.9.13' ] ]
verbose parsed url { pathname: '~0.9.13', path: '~0.9.13', href: '~0.9.13' }
verbose addNamed [ 'socket.io', '~0.9.13' ]
verbose addNamed [ null, '>=0.9.13- <0.10.0-' ]
silly name, range, hasData [ 'socket.io', '>=0.9.13- <0.10.0-', false ]
verbose raw, before any munging node-static
verbose url resolving [ 'https://registry.npmjs.org/', './node-static' ]
verbose url resolved https://registry.npmjs.org/node-static
http GET https://registry.npmjs.org/node-static
verbose raw, before any munging socket.io
verbose url resolving [ 'https://registry.npmjs.org/', './socket.io' ]
verbose url resolved https://registry.npmjs.org/socket.io
http GET https://registry.npmjs.org/socket.io
ERR! Error: failed to fetch from registry: socket.io
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.g (events.js:156:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.parserOnIncomingClient (as onIncoming) (http.js:1256:7)
ERR! You may report this log at:
ERR!     http://bugs.debian.org/npm
ERR! or use
ERR!     reportbug --attach /home/stefano/controldeck.js-master/npm-debug.log npm
ERR!
ERR! System Linux 3.8.0-35-generic
ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
ERR! cwd /home/stefano/controldeck.js-master
ERR! node -v v0.6.19
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: socket.io
verbose exit [ 1, true ]

**Comment by macsteu** [comment]
Solved installing the latest version of node.js.
